In [1]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[86, 28],
       [24,  2],
       [72, 79],
       [59, 83],
       [ 6, 30],
       [74, 22],
       [67, 82],
       [ 5, 98],
       [70, 62],
       [40, 49]])

In [6]:
scaler_model = MinMaxScaler()

In [7]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
scaler_model.fit(data)

/home/cguertz/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
scaler_model.transform(data)

array([[1.        , 0.27083333],
       [0.2345679 , 0.        ],
       [0.82716049, 0.80208333],
       [0.66666667, 0.84375   ],
       [0.01234568, 0.29166667],
       [0.85185185, 0.20833333],
       [0.7654321 , 0.83333333],
       [0.        , 1.        ],
       [0.80246914, 0.625     ],
       [0.43209877, 0.48958333]])

In [10]:
scaler_model.fit_transform(data)

/home/cguertz/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[1.        , 0.27083333],
       [0.2345679 , 0.        ],
       [0.82716049, 0.80208333],
       [0.66666667, 0.84375   ],
       [0.01234568, 0.29166667],
       [0.85185185, 0.20833333],
       [0.7654321 , 0.83333333],
       [0.        , 1.        ],
       [0.80246914, 0.625     ],
       [0.43209877, 0.48958333]])